name: focus_on_it_example
description: A new Flutter module project.
publish_to: none

version: 1.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  focus_on_it:
    path: ../
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: br.com.luanemanuel.focus_on_it_example
    iosBundleIdentifier: br.com.luanemanuel.focus_on_it_example
