name: focus_on_it
description: Get notified when a widget is focused or unfocused and react to it.
version: 2.0.0
repository: https://github.com/luanemanuel/focus_on_it/tree/master
issue_tracker: https://github.com/luanemanuel/focus_on_it/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2
